### ISSUE TITLE
Novas informações no tailwind-css.md

### ISSUE THREAD

**Issue by tavareshenrique** [gatsbyjs/gatsby-pt-BR#171]
### Descrição
Eu fui responsável por traduzir o arquivo [tailwind-css.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/tailwind-css.md) e recentemente, descobri que esse arquivo na versão original foi adicionado mais uma "Option" , no caso a **Option #3: SCSS**. Quando eu traduzi, só tinha até a **Option #2: CSS-in-JS**. 

Vocês me permitem adicionar a tradução da  **Option #3: SCSS** no `tailwind-css.md`?

> Link com a **Option #3: SCSS**
> https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/tailwind-css.md

**Comment by iaurg** [comment]
Perfeito, pode abrir uma no PR com adição deste novo item, o que acha? Assim conseguimos manter as traduções alinhadas com as atualizações.

Com certeza futuramente teremos novas situações como essa.

Obrigado pela observação.

**Comment by tavareshenrique** [comment]
Perfeito, @iaurg! Deixa comigo, irei abrir uma PR resolvendo isso.

Eu que agradeço pelo retorno!!!

**Comment by jay-jlm** [comment]
@tavareshenrique consegue trocar o link que vc incluiu para o site para o link do .md atualizado no repósitorio da documentacao em ingles?
Acredito que isso vai ajudar muito para os revisores

**Comment by tavareshenrique** [comment]
Ótima dica @jay-jlm, está feito! 
Obrigado!

**Comment by jay-jlm** [comment]
Oops, na verdade ia pedir para incluir na descrição da PR, na pressa me enganei.
Acabei de revisar a PR lá, obrigado!

**Comment by tavareshenrique** [comment]
Está sendo resolvido na #173
