### ISSUE TITLE
Sugestão: Adicionar links dos arquivos disponíveis nas batches de tradução

### ISSUE THREAD

**Issue by vinifraga** [gatsbyjs/gatsby-pt-BR#172]
Boa tarde pessoal, o que acham de adicionar o link dos arquivos que ainda não foram distribuídos/corrigidos na listagem das batches pro pessoal conseguir identificar mais facilmente?
Por exemplo:

- [x] headless-cms.md (**@lucas-mdiniz**) :heavy_check_mark: [#87](https://github.com/gatsbyjs/gatsby-pt-BR/pull/87)
- [ ] creating-and-modifying-pages.md (**@RodrigoEC**) :running_man: 
- [ ] [schema-sift.md](https://github.com/gatsbyjs/gatsby-pt-BR/blob/master/docs/docs/schema-sift.md)

Se quiser posso fazer esse mapeamento e mandar pra vocês.

**Comment by iaurg** [comment]
Acho que seria uma boa, evita ficar buscando. Podemos adicionar o link nos que ainda não foram traduzidos.

**Comment by vinifraga** [comment]
@iaurg certo, vou começar a fazer. Por onde mando o texto com essas modificações?

**Comment by vinifraga** [comment]
Pessoal, eu praticamente terminei o arquivo, mas não consegui encontrar no repo:
- todos os arquivos do docs/glossary
- todos os arquivos do docs/recipes
- o arquivo getting-started.md do docs/themes
Vou enviar por aqui o que fiz. Qualquer crítica ou sugestão só falar.
[gastby.zip](https://github.com/gatsbyjs/gatsby-pt-BR/files/4112680/gastby.zip)

**Comment by vinifraga** [comment]
Fecharei a issue porque a lista já não está mais atualizada
