### ISSUE TITLE
Como traduzir o termo "source plugin"?

### ISSUE THREAD

**Issue by jay-jlm** [gatsbyjs/gatsby-pt-BR#21]
### Definição do termo original em inglês

> Source Plugin
> A plugin that adds additional data sources to Gatsby that can then be queried by your pages and components.

### Significado relevante de 'source':
Do Collins English Dictionary (trecho):

> verb
> In business, if a person or firm _sources_ a product or a raw material, they find someone who will supply it.

Acredito que uma localização bem sucedida seria uma que conseguisse manter essa idéia de consumir um recurso (no caso, dados) a partir de uma fonte que fornece os dados.

**Comment by abnersajr** [comment]
O termo plugin por si só não é comumente traduzido para o português. Uma sugestão seria `plugin para fonte de dados` nesse caso.

**Comment by rafaeelaudibert** [comment]
Apenas uma outra tradução possível: `plugin fornecedor (de dados)`

**Comment by Italox** [comment]
Ainda não encontrei nenhuma outra tradução para Source Plugin, nos outros repositórios estão:
ES - "Source plugins"
FR - Les plug-ins de source

Talvez chamar apenas de Plugin? Ficaria muito simples?

Creio que a tradução pode variar de acordo com o contexto da frase/página, tendo uma tradução maleável que se adeque. 

A referência do Gatsby para plugin é [essa página](https://www.gatsbyjs.org/plugins/), o que eles são? Pacotes? Melhorias? Ambos? Tendo a ideia de para onde referencia podemos pensar melhor no termo.

**Comment by jay-jlm** [comment]
@Italox  O significado que está descrição da issue foi retirado do glossário da documentação oficial do Gastby. 
Obrigado pela pesquisa, aparentemente nessas outras versões eles decidiram deixar o termo em inglês. 🤷‍♂

**Comment by Italox** [comment]
> @Italox O significado que está na descrição da issue foi retirado do glossário da documentação oficial do Gastby.
> Obrigado pela pesquisa, aparentemente nessas outras versões eles decidiram deixar o termo em inglês. man_shrugging

Vamos seguir a mesma ideia?

**Comment by jay-jlm** [comment]
> Vamos seguir a mesma ideia?
Particularmente eu nao gosto de deixar os termos em inglês, evito ao máximo.
Dito isso, acho uma opção válida, sim. Não tenho opinião consolidada ainda.

**Comment by luizcieslak** [comment]
No #34 eu deixei ele na tradução direta: `Plugins de origem`

**Comment by jessescn** [comment]
Eu recomendo o uso de `Plugin nativo`

**Comment by jay-jlm** [comment]
> Eu recomendo fortemente o uso de `Plugin nativo`

Qual o motivo?

**Comment by jay-jlm** [comment]
Mais usado onde? Tem algum link?

**Comment by jessescn** [comment]
Creio que não existe um link com uma pesquisa. @jay-jlm qual você recomenda então?

**Comment by jay-jlm** [comment]
Estou OK com qualquer tradução que preserve o significado do termo original como exemplificado na descrição da issue. `plugin nativo` vi apenas usado no contexto de outras tecnologias (como por exemplo o Cordova), mas se referir a plugins com funções bem diferentes dos source plugins do Gatsby. Mas se tiver alguma referência que traduz 'source plugin' como 'plugin nativo'  tenho interesse em conhecer.

**Comment by gvarandas** [comment]
No contexto da documentação, a palavra `source` indica uma fonte de dados, literalmente.
Não seria recomendado então traduzir isso como `plugins de fontes (de dados?)`?

**Comment by jessescn** [comment]
Dependendo do contexto, mas na maioria do casos ele se refere a um plugin que já vem 
 no gatsby (nativo do Gatsby)

**Comment by gvarandas** [comment]
A frase`Source plugins fetch data from their source. E.g. the filesystem source plugin knows how to fetch data from the file system` está definindo a origem dos dados, a fonte.
Os _source plugins_ são plugins para puxar dados de origens diversas, não necessariamente “nativos do Gatsby”. Sendo assim, não faz sentido traduzir isso como `plugin nativo`, mas sim `plugin de origem`, ou `plugin de fonte de dados`.

**Comment by Italox** [comment]
Creio que podemos desconsiderar o termo `plugin nativo`, porque vi que o Gatsby pede para instalar os plugins enquanto você está desenvolvendo, então se preciso instalar ele deixa de ser nativo. Acompanhei a [página](https://www.gatsbyjs.org/tutorial/part-five/) e fui seguindo o tutorial:

```
First, install the plugin at the root of the project:

npm install --save gatsby-source-filesystem
```

**Comment by rafaeelaudibert** [comment]
Sendo considerado como "plugin de origem" ou "plugin de extração", de acordo com o contexto, em #151

**Comment by Rychillie** [comment]
Plugin não poderia ser uma tradução para Conector?

**Comment by jessescn** [comment]
@Rychillie o termo plugin é comumente usado, diferente da sua tradução mesmo. O ponto seria o _source_ mesmo.

**Comment by iaurg** [comment]
@Rychillie É como o @jessescn mencionou, o pessoal da área já conhece muito o termo "plugin", o que complica é a tradução do conjunto "Source Plugin" que pode ter vários entendimentos de acordo com o contexto.

**Comment by henry-ns** [comment]
Que tal usar a tradução e em seguida entre parênteses o termo original para esses casos?

Que no caso ficária: `Plugins de origem (source plugins)`
